services:
  python3:
    container_name: python3-container
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - .venv:/app/.venv
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    extra_hosts:
      - localhost:host-gateway
    stdin_open: true
    tty: true
    

  mysql:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      # MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      
      TZ: "Asia/Tokyo"
    healthcheck:
      test: mysqladmin ping -h ${DATABASE_HOST} -u ${DATABASE_USER} --password=${DATABASE_PASSWORD}
      interval: 1s
      retries: 20
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf